# Generated by Django 3.1.7 on 2021-03-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0003_auto_20210303_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstock',
            name='mStock_product_detail',
            field=models.CharField(max_length=50),
        ),
    ]
