# Generated by Django 3.1.7 on 2021-03-05 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0004_auto_20210303_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstock',
            name='mStock_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
