# Generated by Django 3.1.7 on 2021-03-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0006_animaldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaldetail',
            name='animalDetail_product',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='dairyapp.mproduct'),
            preserve_default=False,
        ),
    ]
