# Generated by Django 3.1.7 on 2021-03-16 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0007_animaldetail_animaldetail_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('assets_id', models.AutoField(primary_key=True, serialize=False)),
                ('particular', models.CharField(max_length=80)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('qty', models.FloatField()),
                ('rate', models.FloatField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('particular', models.CharField(max_length=80)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('qty', models.FloatField()),
                ('rate', models.FloatField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='animaldetail',
            name='animalDetail_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
