# Generated by Django 3.1.7 on 2021-03-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0008_auto_20210316_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
