# Generated by Django 3.1.7 on 2021-03-18 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0012_auto_20210318_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerledger',
            name='customer',
        ),
        migrations.AlterField(
            model_name='mproductsell',
            name='buyer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dairyapp.customer'),
        ),
        migrations.AlterField(
            model_name='mproductsell',
            name='mProductSell_paymentMethod',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='mproductsell',
            name='milk_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dairyapp.mproduct'),
        ),
    ]
